[package]
name = "py-checked-exceptions"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
description = "A static analyzer that enforces exception documentation in Python code"
homepage = "https://github.com/cstruct/py-checked-exceptions"
repository = "https://github.com/cstruct/py-checked-exceptions"
readme = "README.md"
keywords = ["python", "static-analysis"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.98"
itertools = "0.15.0"
ruff_db = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6", features = ["os"]}
ruff_python_ast = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ruff_text_size = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ruff_source_file = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ruff_memory_usage = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ruff_ranged_value = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ty_static = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ty_project = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ty_module_resolver = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ty_python_core = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
ty_python_semantic = { git = "https://github.com/cstruct/ruff.git", rev = "f8b44c6bc6a427130b851d84acbaf42fb9ec20c6" }
indicatif = "0.18.0"
tracing = "0.1.41"
rayon = "1.10.0"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
clap = { version = "4.5.43", features = ["derive", "env"] }
salsa = { version = "0.28.2", default-features = false, features = [
    "compact_str",
    "macros",
    "salsa_unstable",
    "inventory",
] }
get-size2 = { version = "0.11.0", features = [
    "derive",
    "smallvec",
    "hashbrown",
    "compact-str",
] }
colored = "3.0.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-flame = "0.2.0"
jiff = "0.2.15"
clearscreen = "4.0.2"
serde = { version = "1.0.219", features = ["derive"] }
toml = "1.0.0"
